sodenn/2do-txt

public/locales/de/translation.json
public/locales/en/translation.json
src/components/AddTaskButton.tsx
src/components/Kbd.tsx
src/components/Page.tsx
src/components/SideSheet.tsx
src/components/SideSheetButton.tsx
src/components/TaskContextMenu.tsx
src/components/TaskList/TaskList.tsx
src/components/TodoFileDownloadButton.tsx

feat: show keyboard shortcuts for the most important actions.

---

src/utils/task-styles.ts
src/utils/task.tsx

fix: Make sure that there are line breaks in the task text

---

public/locales/de/translation.json
public/locales/en/translation.json
src/components/AppRouter.tsx
src/components/Header.tsx
src/components/Page.tsx
src/components/SideSheet.tsx
src/components/TaskList/TaskList.tsx
src/components/TaskListItem.tsx
src/components/TaskListItemMenu.tsx
src/data/AppContext.tsx
src/data/TaskContext.ts
src/utils/array.ts
src/utils/task-list.ts
src/utils/task.tsx

feat: display sorted tasks in a grouped list

---

src/components/TaskDialog.tsx
src/components/TaskEditor/TaskEditor.tsx
src/components/TaskForm.tsx

feat: full-screen task dialog for mobile devices

---

src/components/TaskDialog.tsx
src/components/TaskEditor/TaskEditor.tsx
src/components/TaskForm.tsx

fix: increase the delay before the text field is focused

---

src/data/TaskContext.ts
src/utils/date.ts
src/utils/notifications.ts
src/utils/task-list.ts

feat: use date-fns package for parsing and comparing date objects

---

src/components/TaskDialog.tsx
src/components/TaskEditor/TaskEditor.tsx

fix: rollback full-screen task dialog because of scrolling issues

---

src/components/TaskBody.tsx
src/components/TaskEditor/mention-styles.ts
src/components/TaskListItem.tsx
src/utils/task-styles.ts
src/utils/task.tsx

feat: improve task list item styling

---

src/components/TaskList/TaskList.tsx

fix: task list subheader gradient

---

public/locales/de/translation.json
src/components/TodoFileDownloadButton.tsx

fix: hide download button is no todo.txt is open

---

src/index.css

fix: disable pull-to-refresh

---

src/components/TaskList/TaskList.tsx

fix: avoid scrollbar overlapping

---

.run/Run all Tests.run.xml
public/locales/de/translation.json
public/locales/en/translation.json
src/components/Filter.tsx
src/components/TaskList/TaskList.tsx
src/data/AppContext.tsx
src/data/TaskContext.ts
src/utils/array.ts
src/utils/task-list.test.ts
src/utils/task-list.ts

feat: add more sorting options for the task list

---

src/components/Filter.tsx
src/data/TaskContext.ts
src/utils/task-list.test.ts
src/utils/task-list.ts

fix(Filter): only show filters for incomplete tasks when completed tasks are hidden

---

src/utils/task-list.test.ts
src/utils/task-list.ts

feat(TaskList): multiple filter conditions are ANDed together

---

src/components/FileSelect.tsx
src/components/TaskDialog.tsx
src/components/TaskForm.tsx

style(TaskForm): hide creation date input field when creating new tasks

---

public/locales/de/translation.json
public/locales/en/translation.json
src/components/Filter.tsx
src/data/FilterContext.ts
src/utils/task-list.test.ts
src/utils/task-list.ts

feat(Filter): limit filter types to AND and OR

---

public/locales/de/translation.json
public/locales/en/translation.json
src/components/FileMenu.tsx
src/components/Filter.tsx
src/components/Kbd.tsx
src/components/Page.tsx
src/components/ShortcutsDialog.tsx
src/data/ProviderBundle.tsx
src/data/ShortcutsDialogContext.ts
src/data/SideSheetContext.ts
src/utils/testing.tsx
tests/filter.spec.ts

feat: shortcut for clearing the task filter

---

README.md

chore(README): update web app URL

---

src/components/FilePicker.tsx

fix(FilePicker): make files in the 2do.txt folder selectable via the file picker

---

.run/Playwright (Chromium, Clipboard).run.xml
.run/Playwright (Chromium, current file).run.xml
.run/Playwright (Safari, Clipboard).run.xml
.run/Playwright (Safari, current file).run.xml
src/components/SideSheet.tsx
tests/filter.spec.ts

fix: keyboard shortcuts don't work

---

src/data/CloudStorageContext/CloudStorageContext.tsx
src/data/CloudStorageContext/webdav-client/put-file-contents.ts
src/data/TaskContext.tsx
src/utils/request.ts

fix(Tauri): failed to parse response body

---

src/utils/task.test.ts
src/utils/task.tsx

fix(recurring task): avoid accidentally removing spaces when creating recurring tasks

---

.vscode/launch.json
src/components/AppThemeProvider.tsx
src/components/FileCreateDialog.tsx
src/components/WebDAVDialog.tsx
src/native-api/network.ts
src/utils/CloudStorage/webdav-storage.ts

fix(WebDAV): fetching file metadata from WebDAV server

---

ios/App/Podfile
src/stores/cloud-store.ts
src/utils/CloudStorage/lib/core/storage/storage.ts
src/utils/CloudStorage/lib/webdav/webdav-client.ts
src/utils/CloudStorage/useCloudStorage.tsx

fix(WebDAV): fix WebDAV sync error on iOS

---

src/components/FileManagementDialog/OpenFileList.tsx
src/components/Page.tsx
src/components/SideSheet.tsx
src/stores/scrolling-store.ts
src/utils/CloudStorage/useCloudStorageEffect.ts

fix(): make sure the content is scrolled to the top before pull-to-refresh function is triggered
